<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsexzzx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsexzzx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCsexzzx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCsexzzx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCsexzzx\appProdProjectContainer(array(
    'container.build_hash' => 'Csexzzx',
    'container.build_id' => '0001307c',
    'container.build_time' => 1540838870,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsexzzx');
